### PR TITLE
Support for non-standard hyphenation

### PR DESCRIPTION
**Pull request by bertfrees**

### CODE REVIEW

**Comment by josteinaj** [comment]
Seems to work great. Thanks!

Rebased and merged here: c129d56ea60ed469b2f9b83ac0d278beec0bae01...177daa6f8dddd0f4f7fd8e95bbb4cb9ae0f498d5

Released as version 1.1.0 here: https://github.com/nlbdev/spell-no/packages/1356122

@bertfrees will you include version 1.1.0 in the next Pipeline 2 release? Is there one planned?

**Comment by bertfrees** [comment]
Thanks. I'm including it as we speak. It's a bit annoying that you need to authenticate in order to download from a Github Maven repo. I hope they will change that at one point.

I have no new Pipeline release planned yet.

**Comment by josteinaj** [comment]
Oh, I didn't know that. That's annoying. I guess that's gonna be a problem if using the updater mechanism etc. as well. If there's any settings I can change to disable that, let me know. I don't see any settings for it yet.

We were hoping to start testing this before summer. Do you think there could be a release before summer (i.e. some time in May)?

**Comment by josteinaj** [comment]
I could try mirroring the files in github pages if that helps to work around the authentication issue.

**Comment by bertfrees** [comment]
> I guess that's gonna be a problem if using the updater mechanism etc. as well.

I only fetch the ZIP at build time. The patterns file is copied into the libhyphen-utils module. I've even committed to file to git because of the authentication issue, so that you only need to authenticate once, when you've updated the version number.

The best solution I think is to use Maven Central. Or maybe Github will provide a setting to disable the authentication.

> Do you think there could be a release before summer (i.e. some time in May)?

Hmm, I'm not sure. I'll try. The change will definitely be available on the master branch before that, and I could push a Docker image tagged with "snapshot", so that you could already start testing that?

**Comment by josteinaj** [comment]
Maven Central would be best, but I think the sonatype distribution workflow is very cumbersome, and making it easy for others to perform a release is important. I might have a look at alternatives in the future. I've seen some suggest switching to GitLab, since it doesn't require authentication for its maven repository. I've also seen some using github pages with success.

A snapshot docker image would be great! That's all we need.

**Comment by bertfrees** [comment]
> A snapshot docker image would be great! That's all we need.

Working on it! By the way I'm also moving to a new repository with a better name: [daisyorg/pipeline](https://hub.docker.com/r/daisyorg/pipeline). The tag will be called "latest-snapshot".

**Pull request closed without merging**
